=== Formatter/account-aggregator-standards/schemas/infrastructure_investment_trusts/invit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:aa="http://api.rebit.org.in/FISchema/invit" elementFormDefault="qualified"
  targetNamespace="http://api.rebit.org.in/FISchema/invit"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.1">
  <!--  -->

  <xs:simpleType name="version">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
      <xs:maxInclusive value="2.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HoldingEmail">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HoldingPan">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][0-9][0-9][0-9][0-9][a-zA-Z]"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HoldersTypes">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SOLE"/>
      <xs:enumeration value="JOINT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TransactionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BUY"/>
      <xs:enumeration value="SELL"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HoldingStatus">
    <xs:restriction base="xs:string">
      <xs:enumeration value="INDIVIDUAL"/>
      <xs:enumeration value="MINOR"/>
      <xs:enumeration value="HUF"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HoldingNominee">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REGISTERED"/>
      <xs:enumeration value="NOT-REGISTERED"/>
    </xs:restriction>
  </xs:simpleType>
  
  <xs:simpleType name="HoldingSubtype">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ANY-ONE-OR-SURVIVOR"/>
      <xs:enumeration value="EITHER-OR-SURVIVOR"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="HoldingMode">
    <xs:restriction base="xs:string">
      <xs:enumeration value="DEMAT"/>
      <xs:enumeration value="PHYSICAL"/>
    </xs:restriction>
  </xs:simpleType>

  
  <!--  -->
  <xs:element name="Account">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Profile" minOccurs="0"/>
        <xs:element ref="aa:Summary"/>
        <xs:element ref="aa:Transactions" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="linkedAccRef" use="required" type="xs:string"/>
      <xs:attribute name="maskedAccNumber" use="required" type="xs:string"/>
      <xs:attribute name="version" use="required" type="xs:string"/>
      <xs:attribute name="type" use="required" type="xs:string" fixed="invit"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Profile">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holders"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Summary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Investment"/>
      </xs:sequence>
      <xs:attribute name="investmentValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="currentValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>

    </xs:complexType>
  </xs:element>


  <xs:element name="Investment">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holdings"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="Holdings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holding"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <xs:element name="Holders">
    <xs:complexType>

      <xs:sequence>
        <xs:element ref="aa:Holder"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>






  <xs:element name="Holder">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of primary holder operating the account. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="dob" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date of birth of primary account holder.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="mobile" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Primary mobile number of account holder. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="address" type="xs:string">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="landline" type="xs:string">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="email" use="required" type="aa:HoldingEmail">
        <xs:annotation>
          <xs:documentation> Email ID of primary account holder. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="dematId" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Demat ID assigned or issued to investor  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="pan" use="required" type="aa:HoldingPan">
        <xs:annotation>
          <xs:documentation> PAN number of primary account holder.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ckycCompliance" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation> KYC status whether its completed or pending </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="nominee" use="required" type="aa:HoldingNominee">
        <xs:annotation>
          <xs:documentation> Name of nominee associated with the account. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  
  
  <xs:element name="Holding">
    <xs:complexType>
      <xs:attribute name="issuerName" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of party who issued the invit in which investment made.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="isin" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> International Securities Identification Number (ISIN) uniquely identifies a security. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
     
      <xs:attribute name="investmentDateTime" use="required" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation> Investment date time stamp for particular record when investment taken place. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="rate" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Rate or net price on which investment made in security. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
      <xs:attribute name="totalNumberUnits" use="required" type="xs:integer">
        <xs:annotation>
          <xs:documentation> Total number of units issued to investor in the fund opted. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="lastClosingRate" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Closing Price or Rate on which security trade in the open market </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="description" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Description or details of security in which investment made. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      
    </xs:complexType>
  </xs:element>

  <xs:element name="Transactions">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Transaction"/>
      </xs:sequence>
      <xs:attribute name="startDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Start date of investment since when it is applicable </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="endDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> End date of investment when tenure get complete </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Transaction">
    <xs:complexType>
      <xs:attribute name="txnId" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Transaction ID recorded or captured for investment made  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="isin" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> International Securities Identification Number (ISIN) uniquely identifies a security.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="issuerName" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of issuer </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="symbol" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Symbol of the securities in which investment made and hold by investor. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="exchange" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Stock Exchange on which security is traded </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="transactionDescription" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Description or details of transaction in which investment made. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="transactionDateTime" use="required" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation> Transaction date time stamp for particular record when investment taken place. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="price" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Price or market value on investment taken place. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="unitsType" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="numUnitsTransacted" use="required" type="xs:integer">
        <xs:annotation>
          <xs:documentation> Number of unit alloted in portfolio as per transaction conducted. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tradeValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Trade value of investment as per market price.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="totalCharge" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Total charges includes finance charge, STT or other taxes/charge implied on investment. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="otherCharges" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Other charge applied on the investment if applicable.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>

    </xs:complexType>
  </xs:element>
</xs:schema>

=== Formatter/account-aggregator-standards/schemas/infrastructure_investment_trusts/INVIT.xml
<?xml version="1.0" encoding="UTF-8"?>
<Account xmlns="http://api.rebit.org.in/FISchema/invit"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://api.rebit.org.in/FISchema/bonds ../FISchema/invit.xsd"
	linkedAccRef="" maskedAccNumber="" version="1.0" type="invit">
	<Profile>
		<Holders>
			<Holder name="" dob="2002-09-24" mobile="91729391923" nominee="NOT-REGISTERED"
				dematId="" email="qw@gmail.com" pan="AAAPL1234C" ckycCompliance="true"/>
		</Holders>
	</Profile>



	<Summary investmentValue="10.0" currentValue="20.0">
		<Investment>

			<Holdings>
				<Holding isin="" issuerName="" investmentDateTime="2017-12-31T16:20:00-04:00"
					rate="20.0" totalNumberUnits="10" lastClosingRate="234.09" description=""/>
			</Holdings>

		</Investment>
	</Summary>
	<Transactions startDate="2002-09-24" endDate="2002-09-24">
		<Transaction txnId="" transactionDateTime="2017-12-31T16:20:00-04:00" isin="" issuerName=""
			symbol="" exchange="" transactionDescription="" price="100" unitsType=""
			numUnitsTransacted="10" tradeValue="230.05" totalCharge="200.0" otherCharges="10.0"/>

	</Transactions>
</Account>
