=== Formatter/account-aggregator-standards/schemas/government_securities/govt_securities.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:aa="http://api.rebit.org.in/FISchema/govt_securities" elementFormDefault="qualified"
  targetNamespace="http://api.rebit.org.in/FISchema/govt_securities"
  xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning" vc:minVersion="1.0" vc:maxVersion="1.1">
  <!--  -->
  <xs:simpleType name="SummaryScheme">
    <xs:restriction base="xs:string">
      <xs:enumeration value="FIXED_INTEREST_RATE"/>
      <xs:enumeration value="T_NOTES"/>
      <xs:enumeration value="T_BONDS"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="version">
    <xs:restriction base="xs:float">
      <xs:minInclusive value="0.0"/>
      <xs:maxInclusive value="2.0"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HolderEmail">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^\.]+\..+"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HolderPan">
    <xs:restriction base="xs:string">
      <xs:pattern value="[a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][a-zA-Z][0-9][0-9][0-9][0-9][a-zA-Z]"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HolderAadhar">
    <xs:restriction base="xs:string">
      <xs:pattern value="[0-9]{12}"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HolderType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SINGLE"/>
      <xs:enumeration value="JOINT"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HoldingType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SOLE"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="NomineeType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REGISTERED"/>
      <xs:enumeration value="NOT_REGISTERED"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="HoldingNominee">
    <xs:restriction base="xs:string">
      <xs:enumeration value="REGISTERED"/>
      <xs:enumeration value="NOT-REGISTERED"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="InterestComputationType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SIMPLE"/>
      <xs:enumeration value="COMPOUND"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="CompoundingFrequencyType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MONTHLY"/>
      <xs:enumeration value="HALF_YEARLY"/>
      <xs:enumeration value="YEARLY"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>


  <xs:simpleType name="InterestPayoutType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MONTHLY"/>
      <xs:enumeration value="HALF_YEARLY"/>
      <xs:enumeration value="YEARLY"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TransactionType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="BUY"/>
      <xs:enumeration value="SELL"/>
      <xs:enumeration value="OTHERS"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  -->
  <xs:element name="Account">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Profile" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="aa:Summary" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="aa:Transactions" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="maskedAccNumber" use="required" type="xs:string"/>
      <xs:attribute name="linkedAccRef" use="required" type="xs:string"/>
      <xs:attribute name="version" use="required" type="aa:version"/>
      <xs:attribute name="type" use="required" type="xs:string" fixed="govt_securities"/>
    </xs:complexType>
  </xs:element>

  <xs:element name="Profile">
    <xs:annotation>
      <xs:documentation>Basic Profile of the account which should include the Account Owner
        information, maskedAccNumber and linkedAccRef numbers, type of account specific to the FI
        type and any other generic details as might be pertinent for the specified FI type.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holders"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>



  <xs:element name="Summary">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holdings"/>
      </xs:sequence>
      <xs:attribute name="investmentValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Principal or Actual amount of investment   </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="currentValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Current value of investment as on date  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Holders">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holder"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Holder">
    <xs:complexType>
      <xs:attribute name="name" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of primary holder operating the account </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="holdingType" type="aa:HoldingType">
        <xs:annotation>
          <xs:documentation> Holding types whether SOLO or others </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="address" use="optional" type="xs:string">
        <xs:annotation>
          <xs:documentation>  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="nominee" use="required" type="aa:HoldingNominee">
        <xs:annotation>
          <xs:documentation> Name of nominee associated with the account. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="email" type="aa:HolderEmail">
        <xs:annotation>
          <xs:documentation> Email ID of primary account holder  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="landline" use="optional" type="xs:string">
        <xs:annotation>
          <xs:documentation> landline number of primary account holder </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="mobile" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Primary mobile number of account holder  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="dematId" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Demat ID assigned or issued to investor </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="pan" use="required" type="aa:HolderPan">
        <xs:annotation>
          <xs:documentation> PAN number of primary account holder </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="dob" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date of birth of primary account holder </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="ckycCompliance" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation> KYC status whether its completed or pending  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>

  <xs:element name="Holdings">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Holding"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Holding">
    <xs:annotation>
      <xs:documentation>The value of the account, term of the deposits if relevant and any other
        data that summarizes the funds in the account. </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:attribute name="scheme" use="required" type="aa:SummaryScheme"> 
        <xs:annotation>
          <xs:documentation> Name of scheme choosen by person for the investment. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="isin" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> International Securities Identification Number (ISIN) uniquely identifies a security.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="units" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Units allotted in folio till date  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="faceValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Face value on which investment made in govt securities  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="symbol" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Symbol of the securities in which investment made and hold by investor </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="issuerName" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of party who issued the govt security in which investment made </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="description" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Description or details of security in which investment made </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="creditRating" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Rating of the fund invested assigned by credit rating agencies </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="creditRatingAgency" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Name of rating agency who had rated the fund </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="taxable" use="required" type="xs:boolean">
        <xs:annotation>
          <xs:documentation> Status whether investment is taxable or not  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="issueRate" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Rate or net price on which investment made in security </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="issueDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Issue date on which investment made in particular security  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="principleAmount" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Principal or Actual amount of investment  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tenureYears" use="required" type="xs:positiveInteger">
        <xs:annotation>
          <xs:documentation> Years which are passed since investment made  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tenureMoths" use="required" type="xs:positiveInteger">
        <xs:annotation>
          <xs:documentation> Months which are passed since investment made  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tenureDays" use="required" type="xs:positiveInteger">
        <xs:annotation>
          <xs:documentation> Days which are passed since investment made  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="couponRate" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Rate or market price on which coupon is purchased </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="maturityDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date of maturity for investment   </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="coupanComputation" use="required" type="aa:InterestComputationType">
        <xs:annotation>
          <xs:documentation> Whether interest is to be Compound or Simple </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="coupanPaymentDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date on which payment made for coupon purchased </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="autionDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date when auction taken place for particular  investment security </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="compoundingFrequency" use="required" type="aa:CompoundingFrequencyType">
        <xs:annotation>
          <xs:documentation> Frequency at which interest is compounded - monthly/quarterly/annually. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="interestPayout" use="required" type="aa:InterestPayoutType">
        <xs:annotation>
          <xs:documentation> Amount of interest which is paid to investor till date </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="accruedInterestAmount" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> The amount of interest that has been incurred, as of a specific date  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="interestOnMaturity" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Total amount of interest which is to be paid on maturity  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="lastTradedRate" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Last rate on which security traded in the open market </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="lastTradedDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Date of secuirties on which last trade happened </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Transactions">
    <xs:annotation>
      <xs:documentation>Details of all transactions that have been posted in an account.
      </xs:documentation>
    </xs:annotation>
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="aa:Transaction"/>
      </xs:sequence>
      <xs:attribute name="startDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> Start date of investment since when it is applicable.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="endDate" use="required" type="xs:date">
        <xs:annotation>
          <xs:documentation> End date of investment when tenure get complete.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
  <xs:element name="Transaction">
    <xs:complexType>
      <xs:attribute name="txnId" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Transaction ID recorded or captured for investment made. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="isin" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> International Securities Identification Number (ISIN) uniquely identifies a security. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="narration" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Nararation is additional details in form of decription of remark associated with investment. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="transactionDateTime" use="required" type="xs:dateTime">
        <xs:annotation>
          <xs:documentation> Transaction date time stamp for particular record when investment taken place.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="rate" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Rate or net price on which investment made in security  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="type" use="required" type="aa:TransactionType">
        <xs:annotation>
          <xs:documentation> Type of transaction whether Buy or Sell, etc </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="units" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Units which are alloted in the portfolio of investor. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="currency" use="required" type="xs:string">
        <xs:annotation>
          <xs:documentation> Currency in which transaction taken place. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="tradeValue" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Trade value of investment as per market price. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="totalCharge" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Total charges includes finance charge, STT or other taxes/charge implied on investment. </xs:documentation>
        </xs:annotation>
      </xs:attribute>
      <xs:attribute name="otherTaxes" use="required" type="xs:float">
        <xs:annotation>
          <xs:documentation> Additonal or any type of tax chareged on the investment.  </xs:documentation>
        </xs:annotation>
      </xs:attribute>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Formatter/account-aggregator-standards/schemas/government_securities/Govt_securities.xml
<?xml version="1.0" encoding="UTF-8"?>
<Account xmlns="http://api.rebit.org.in/FISchema/govt_securities"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://api.rebit.org.in/FISchema/govt_securities ../FISchema/govt_securities.xsd"
    linkedAccRef="" maskedAccNumber="" version="1.0" type="govt_securities">
    <Profile>
        <Holders>
            <Holder name="" dob="2002-09-24" mobile="91729391923" nominee="NOT-REGISTERED"
                dematId="" email="qw@gmail.com" pan="AAAPL1234C" ckycCompliance="true"/>
        </Holders>
    </Profile>

    <Summary investmentValue="200" currentValue="205">
        <Holdings>
            <Holding scheme="FIXED_INTEREST_RATE" faceValue="19" isin="" units="34" symbol=""
                issuerName="" issueRate="" description="" creditRating="" creditRatingAgency=""
                taxable="true" issueDate="2004-04-12" principleAmount="200" tenureYears="3"
                tenureMoths="36" tenureDays="120" accruedInterestAmount="4" couponRate="6"
                maturityDate="2004-04-12" coupanComputation="COMPOUND"
                coupanPaymentDate="2004-04-12" autionDate="2004-04-12"
                compoundingFrequency="HALF_YEARLY" interestPayout="HALF_YEARLY"
                interestOnMaturity="3" lastTradedDate="2004-04-12" lastTradedRate="6"/>
        </Holdings>
    </Summary>

    <Transactions startDate="2004-04-12" endDate="2004-04-12">
        <Transaction txnId="" isin="" narration="" transactionDateTime="2004-04-12T13:20:00-05:00"
            rate="3" type="BUY" currency="" units="12" tradeValue="23" totalCharge="34"
            otherTaxes="2"/>
    </Transactions>
</Account>
